### ISSUE TITLE
How to specify connection duration?

### ISSUE THREAD

**Issue by jorgeorpinel** [sidecars/python-quickbooks#75]
I noticed the connection of the client is short lived.

The [QBO OAuth Playground](https://appcenter.intuit.com/Playground/OAuth/IA) has an "Access Token Duration" field (by default 120 seconds)

How can we specify a long duration, say an hour?

Thanks

**Comment by cstarner** [comment]
The QuickBooks API uses OAuth 1.0 for authentication, which does not have the concept of "Access Token Duration" built in naturally. According to the QuickBooks API section on OAuth, the Access Tokens[ expire after 180 days](https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app#/Managing_OAuth_access_tokens). This does not seem to be configurable

With the OAuth Playground, the "Access Token Duration" is likely added so that token generated with the Playground don't stick around

**Comment by jorgeorpinel** [comment]
And apparently you can extend the token's life span indefinitely using [Reconnect](https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/oauth_management_api#/Reconnect).
